name: Integration Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - name: Checkout yeoman-api
        uses: actions/checkout@v3
        with:
          path: yeoman-api
      - name: Checkout yeoman-test
        uses: actions/checkout@v3
        with:
          path: yeoman-test
      - name: Checkout yeoman-generator
        uses: actions/checkout@v3
        with:
          repository: yeoman/generator
          path: yeoman-generator
      - name: Checkout yeoman-environment
        uses: actions/checkout@v3
        with:
          repository: yeoman/environment
          path: yeoman-environment
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run yeoman-test test
        run: |
          cd $GITHUB_WORKSPACE/yeoman-test
          npm ci
          npm install ${{ github.repository }}#$GITHUB_SHA
          npm test

      - name: Run yeoman-generator test
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/yeoman-generator
          npm ci
          npm install ${{ github.repository }}#$GITHUB_SHA
          npm test

      - name: Run yeoman-environment test
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/yeoman-environment
          npm ci
          npm install ${{ github.repository }}#$GITHUB_SHA
          npm test
